## Pandas Practice
---

In [ ]:
import pandas as pd

In [ ]:
# Series
data = [100, 234, 43, 141, 99]
series = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])
print(series)
print(series.loc['c'])
print(series.iloc[3])

a    100
b    234
c     43
d    141
e     99
dtype: int64
43
141

In [ ]:
# Filtering series
filtered = series[series >= 200]
print(filtered)

b    234
dtype: int64

In [ ]:
# DataFrames
data = {
    "Name": ["Spongebob", "Patrick", "Squidward"],
    "Age": [30, 35, 50]
}

dataframe = pd.DataFrame(data)
print(dataframe)
print(dataframe.loc[0])

dataframe['Job'] = ["Cook", "N/A", "Cashier"]
print(dataframe)

new_row = pd.DataFrame([{"Name": "Sandy", "Age": 28, "Job": "Engineer"}])
dataframe = pd.concat([dataframe, new_row])
dataframe

        Name  Age
0  Spongebob   30
1    Patrick   35
2  Squidward   50
Name    Spongebob
Age            30
Name: 0, dtype: object
        Name  Age      Job
0  Spongebob   30     Cook
1    Patrick   35      N/A
2  Squidward   50  Cashier

        Name  Age       Job
0  Spongebob   30      Cook
1    Patrick   35       N/A
2  Squidward   50   Cashier
0      Sandy   28  Engineer

In [ ]:
# Reading CSV files
df = pd.read_csv('data/adult.data.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
# Reading JSON files
df = pd.read_json('data/adult.data.json')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
# Accessing data
df = pd.read_csv('data/adult.data.csv')

# Select by columns
print(df[['age', 'sex']])

# Select by rows
print(df.loc[0])
print(df[['age', 'sex']].loc[0:5])

       age     sex
0       39    Male
1       50    Male
2       38    Male
3       53    Male
4       28  Female
...    ...     ...
32556   27  Female
32557   40    Male
32558   58  Female
32559   22    Male
32560   52  Female

[32561 rows x 2 columns]
age                          39
workclass             State-gov
fnlwgt                    77516
education             Bachelors
education-num                13
marital-status    Never-married
occupation         Adm-clerical
relationship      Not-in-family
race                      White
sex                        Male
capital-gain               2174
capital-loss                  0
hours-per-week               40
native-country    United-States
salary                    <=50K
Name: 0, dtype: object
   age     sex
0   39    Male
1   50    Male
2   38    Male
3   53    Male
4   28  Female
5   37  Female

In [ ]:
# Filtering data
df = pd.read_csv('data/adult.data.csv')

reach = df[df['salary'] == ">50K"]
reach.head()

reach_black = df[(df['salary'] == ">50K") & (df['race'] == 'Black')]
reach_black.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
45,57,Federal-gov,337895,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,40,United-States,>50K
117,49,Local-gov,197371,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Black,Male,0,0,40,United-States,>50K
180,44,Local-gov,181344,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,38,United-States,>50K
206,36,Private,128757,Bachelors,13,Married-civ-spouse,Other-service,Husband,Black,Male,7298,0,36,United-States,>50K

In [ ]:
# Aggregation
df = pd.read_csv('data/adult.data.csv')

df.mean(numeric_only=True)
df.sum(numeric_only=True)
df.min(numeric_only=True)
df.count()

# Single Column
df["age"].max()

# Grouping
group = df.groupby('race')
group["hours-per-week"].mean()

race
Amer-Indian-Eskimo    40.048232
Asian-Pac-Islander    40.127045
Black                 38.422855
Other                 39.468635
White                 40.689100
Name: hours-per-week, dtype: float64

In [ ]:
# Data cleaning
df = pd.read_csv('data/adult.data.csv')

df = df.drop(columns=["education-num", 'fnlwgt', 'capital-loss', 'capital-gain'])

df['salary'] = df['salary'].replace({"<=50K": "poor", ">50K": "rich"})
df

,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,poor
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,poor
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,poor
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,poor
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,poor
...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,38,United-States,poor
32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,rich
32558,58,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,40,United-States,poor
32559,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,poor
32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,rich